Repository WildCodeSchool/orleans-0219-php-oryalis, pull requests merged in 2019-07, with the labels that each got.

#63 QCM vue utilisateur to dev
  assets/scss/_vars.scss
  assets/scss/app.scss
  config/services.yaml
  src/Controller/HomeController.php
  src/Controller/NewsController.php
  src/DataFixtures/AnswerFixtures.php
  src/DataFixtures/QuestionFixtures.php
  src/Entity/Answer.php
  src/Entity/Question.php
  src/Repository/AnswerRepository.php
  src/Repository/QuestionRepository.php
  templates/_question.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#93 squelette de la page Veille Règlementaire
  assets/images/Veille_jumb.jpg
  assets/scss/_vars.scss
  assets/scss/app.scss
  public/uploads/employee/herve_vincent.jpg
  public/uploads/employee/nicolas_champagne.jpg
  src/Controller/WatchController.php
  templates/_navbar.html.twig
  templates/watch/index.html.twig
Labels: Reviewed by PO

#89 Création de la page conseil avec son contenu page statique
  assets/images/advice_jumb.jpeg
  assets/images/handshake2.jpg
  assets/images/handshakeT.png
  assets/scss/app.scss
  src/Controller/AdviceController.php
  templates/_navbar.html.twig
  templates/advice/index.html.twig
Labels: Reviewed by PO

#95 Sprint04 us 27 admin ajouter news
  assets/scss/_vars.scss
  assets/scss/appAdmin.scss
  composer.json
  composer.lock
  config/packages/framework.yaml
  src/Controller/NewsController.php
  src/Entity/News.php
  templates/_navbarAdmin.html.twig
  templates/admin_news/_form.html.twig
  templates/admin_news/new.html.twig
Labels: Reviewed by PO

#101 Sprint2 us32 editer un membre
  assets/scss/appAdmin.scss
  public/uploads/employee/herve_vincent.jpg
  public/uploads/employee/nicolas_champagne.jpg
  src/Form/EmployeeType.php
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
Labels: Reviewed by PO

#108 refonte form
  assets/scss/appAdmin.scss
  templates/admin/training/_form.html.twig
  templates/admin/training/index.html.twig
Labels: Reviewed by PO

#112 Fix picture size
  assets/images/BannerHome.jpg
  assets/images/audit.jpeg
  assets/images/audit_1.jpeg
  assets/images/audit_3.jpeg
  assets/images/banner2.jpg
  assets/images/equipe_jumb.jpeg
  assets/images/oryalis.jpg
Labels: Reviewed by PO

#105 fix footer
  assets/images/edit-filled.png
  assets/scss/app.scss
  templates/_Footer.html.twig
Labels: Reviewed by PO

#113 Admin Editer une News
  assets/scss/appAdmin.scss
  src/Controller/NewsController.php
  templates/admin_news/_form.html.twig
  templates/admin_news/edit.html.twig
Labels: Reviewed by PO

#116 admin list des QCM
  src/Controller/QuestionController.php
  src/Entity/Question.php
  src/Form/QuestionType.php
  templates/_navbarAdmin.html.twig
  templates/admin/question/_delete_form.html.twig
  templates/admin/question/_form.html.twig
  templates/admin/question/edit.html.twig
  templates/admin/question/index.html.twig
  templates/admin/question/new.html.twig
  templates/admin/question/show.html.twig
Labels: Reviewed by PO

#117 Sprint4 us38 admin lister normes
  src/Controller/AdminStandardController.php
  src/DataFixtures/StandardFixtures.php
  src/Entity/Standard.php
  src/Form/StandardType.php
  src/Repository/StandardRepository.php
  templates/admin_standard/_delete_form.html.twig
  templates/admin_standard/_form.html.twig
  templates/admin_standard/edit.html.twig
  templates/admin_standard/index.html.twig
  templates/admin_standard/new.html.twig
  templates/admin_standard/show.html.twig
Labels: Reviewed by PO

#118 Page utilisateur les normes
  assets/images/environment.jpg
  assets/images/normes.jpg
  assets/images/quality1.png
  assets/images/security.jpg
  assets/scss/app.scss
  src/Controller/StandardController.php
  templates/_Footer.html.twig
  templates/standards/index.html.twig
Labels: Reviewed by PO

#107 Historique QCM
  assets/scss/app.scss
  src/Controller/QuestionVisitorController.php
  src/Entity/Answer.php
  src/Entity/Question.php
  templates/_question.html.twig
  templates/questions/questions.html.twig
  templates/watch/index.html.twig
Labels: PR prioritaire, Reviewed by PO

#122 Sprint4 us41 supprimer norme
  assets/scss/app.scss
  templates/admin_standard/_delete_form.html.twig
  templates/admin_standard/index.html.twig
Labels: Reviewed by PO

#123 Page new, stylisation du form, ajou d'une } manquante css, liens de l…
  templates/admin_standard/_form.html.twig
  templates/admin_standard/index.html.twig
  templates/admin_standard/new.html.twig
Labels: Reviewed by PO

#133 fix classe css sur le lien des normes dans le footer
  templates/_Footer.html.twig
Labels: Reviewed by PO

#134 Fix equipe nl to br
  src/Entity/Employee.php
  templates/employee/index.html.twig
Labels: Reviewed by PO

#135 Mise en forme de l'edit, modif du d'une class sur le delete pour l'ad…
  templates/admin_standard/_delete_form.html.twig
  templates/admin_standard/edit.html.twig
  templates/admin_standard/index.html.twig
Labels: Reviewed by PO

#136 nl2br sur norme vue et show normes admin
  templates/admin_standard/show.html.twig
  templates/standards/index.html.twig
Labels: Reviewed by PO

#138 Ajout d'onglets dans la Navbar Visitor et Admin, modif du style
  assets/scss/app.scss
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
Labels: Reviewed by PO

#142 Sprint5 us43 news vue
  assets/images/news_jumb.jpeg
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  src/Controller/NewsVisitorController.php
  templates/news/index.html.twig
Labels: Reviewed by PO

#144 Fix liens redirection
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  templates/_Footer.html.twig
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#145 Fix banner10
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/_question.html.twig
  templates/home/index.html.twig
  templates/standards/index.html.twig
Labels: Corrections Done, Reviewed by PO

#146 Modif photos ovale -> ronde, NotNull -> NotBlank, stylisation modif d…
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  src/Entity/Employee.php
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
Labels: Reviewed by PO

#83 contact page form
  .env.test
  .gitignore
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/services.yaml
  phpunit.xml.dist
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  symfony.lock
  templates/_Footer.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/mail/mail.html.twig
  templates/mailBase.html.twig
Labels: Reviewed by PO

#147 Fix admin divers
  src/Entity/News.php
  src/Entity/Standard.php
  src/Entity/Training.php
  src/Form/NewsType.php
  templates/admin/training/_delete_form.html.twig
  templates/admin/training/_form.html.twig
  templates/admin/training/edit.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/new.html.twig
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_news/_delete_form.html.twig
  templates/admin_news/_form.html.twig
  templates/admin_news/edit.html.twig
  templates/admin_news/index.html.twig
  templates/admin_news/new.html.twig
  templates/admin_standard/_form.html.twig
  templates/admin_standard/edit.html.twig
  templates/admin_standard/index.html.twig
  templates/admin_standard/new.html.twig
Labels: Reviewed by PO

#143 Sprint5 us44 pdf
  .env
  assets/scss/app.scss
  assets/scss/pdf.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_snappy.yaml
  src/Controller/TrainingController.php
  symfony.lock
  templates/formations/_trainingDetails.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingPDF.html.twig
  templates/layoutPDF.html.twig
  webpack.config.js
Labels: Reviewed by PO

#155 Fix pictos
  assets/images/audit.png
  assets/images/auditT.png
  assets/images/conseil.png
  assets/images/conseilT.png
  assets/images/environment.jpg
  assets/images/environmentT.png
  assets/images/formation.png
  assets/images/formationT.png
  assets/images/quality1.png
  assets/images/quality1T.png
  assets/images/security.jpg
  assets/images/securityT.png
  assets/images/veille.png
  assets/images/veilleT.png
  templates/home/index.html.twig
  templates/standards/index.html.twig
Labels: Review Requested

#157 Modification du browse en Sélectionner un fichier
  assets/scss/appAdmin.scss
Labels: Reviewed by PO

#159 Fix header
  assets/images/Logo.png
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#160 Dev
  assets/images/Logo.png
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: PR prioritaire, Reviewed by PO

#161 Modif du readme
  README.md
Labels: Reviewed by PO

#162 Fix formation adm vis
  assets/images/datadocke.png
  src/Form/TrainingType.php
  templates/admin/training/_form.html.twig
  templates/admin/training/edit.html.twig
  templates/formations/_trainingDetails.html.twig
  templates/formations/show.html.twig
Labels: Review Requested

#164 Fix news modif
  assets/images/new.jpg
  assets/images/new.png
  src/Controller/HomeController.php
  src/Form/NewsType.php
  templates/home/index.html.twig
Labels: Reviewed by PO

#165 fix qcm
  src/Controller/HomeController.php
  src/DataFixtures/AnswerFixtures.php
  src/DataFixtures/NewsFixture.php
  src/DataFixtures/QuestionFixtures.php
  src/Entity/Question.php
  src/Form/QuestionType.php
  templates/_question.html.twig
  templates/home/index.html.twig
Labels: Corrections Done, Review Requested

#166 Sprint05 us43 login admin
  .env
  assets/scss/app.scss
  composer.lock
  config/packages/dev/swiftmailer.yaml
  config/services.yaml
  src/Controller/AdminSecurityController.php
  src/Entity/Admin.php
  src/Form/MailType.php
  src/Form/SecurityType.php
  templates/base.html.twig
  templates/mail/resetMail.html.twig
  templates/security/forgottenPassword.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
Labels: Corrections Done, Reviewed by PO

#169 fix on qcm edit and questionType
  src/Entity/Question.php
  src/Form/QuestionType.php
  templates/admin/question/index.html.twig
Labels: Reviewed by PO

#171 Responsive du footer sur tablette, suppression des mentions légales q…
  templates/_Footer.html.twig
Labels: Review Requested

#172 Modif responsive sur portable equipe
  templates/employee/index.html.twig
Labels: Review Requested

#173 affichage du mois au lieu du chiffre sur la liste des anciens QCM
  templates/questions/questions.html.twig
Labels: Review Requested

#174 fix on training fields
  assets/images/formationJumb.jpeg
  src/DataFixtures/TrainingFixtures.php
  src/Entity/Training.php
  src/Form/TrainingType.php
  templates/admin/training/_form.html.twig
  templates/admin/training/show.html.twig
  templates/formations/_trainingDetails.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
Labels: Reviewed by PO

#175 style fix on contact page
  assets/images/contact.jpg
  assets/scss/app.scss
  templates/contact/index.html.twig
Labels: Reviewed by PO

#176 Modification de la page veille
  assets/images/veilleO2.png
  assets/images/veilleOutil.png
  assets/scss/app.scss
  templates/watch/index.html.twig
Labels: Reviewed by PO

#177 Element cliquable entièrement
  templates/formations/trainingList.html.twig
Labels: Reviewed by PO

#178 fix fonts size, first letter on all pages
  assets/scss/app.scss
  templates/_Footer.html.twig
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/standards/index.html.twig
Labels: Reviewed by PO

#179 Fix button link
  assets/scss/app.scss
  templates/contact/index.html.twig
  templates/watch/index.html.twig
Labels: Reviewed by PO

#180 fix email config an variable in controller
  src/Controller/ContactController.php
  templates/mail/mail.html.twig
Labels: Reviewed by PO

#181 Dev
  assets/images/contact.jpg
  assets/images/formationJumb.jpeg
  assets/images/veilleO2.png
  assets/images/veilleOutil.png
  assets/scss/app.scss
  src/Controller/ContactController.php
  src/DataFixtures/TrainingFixtures.php
  src/Entity/Training.php
  src/Form/TrainingType.php
  templates/_Footer.html.twig
  templates/admin/training/_form.html.twig
  templates/admin/training/show.html.twig
  templates/contact/index.html.twig
  templates/employee/index.html.twig
  templates/formations/_trainingDetails.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
  templates/home/index.html.twig
  templates/mail/mail.html.twig
  templates/questions/questions.html.twig
  templates/standards/index.html.twig
  templates/watch/index.html.twig
Labels: Reviewed by PO

#182 Suppression du scroll horizontal, changement des titres onglets cohér…
  templates/admin/question/index.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/new.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_news/edit.html.twig
  templates/admin_news/index.html.twig
  templates/admin_news/new.html.twig
  templates/admin_standard/edit.html.twig
  templates/admin_standard/index.html.twig
Labels: Reviewed by PO

#183 general responsive fix
  assets/scss/app.scss
  templates/advice/index.html.twig
  templates/audit/index.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/employee/index.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
  templates/news/index.html.twig
  templates/standards/index.html.twig
  templates/watch/index.html.twig
Labels: Reviewed by PO

#184 Changement des block title pour plus de cohérence
  templates/admin/answer/edit.html.twig
  templates/admin/answer/new.html.twig
  templates/admin/question/edit.html.twig
  templates/admin/question/index.html.twig
  templates/admin/question/show.html.twig
  templates/admin/training/edit.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/show.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_employee/show.html.twig
  templates/admin_news/index.html.twig
  templates/admin_standard/edit.html.twig
  templates/admin_standard/index.html.twig
  templates/admin_standard/show.html.twig
  templates/advice/index.html.twig
  templates/audit/index.html.twig
  templates/contact/index.html.twig
  templates/employee/index.html.twig
  templates/formations/_trainingDetails.html.twig
  templates/home/index.html.twig
  templates/news/index.html.twig
  templates/questions/questions.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
  templates/standards/index.html.twig
Labels: Reviewed by PO

#185 Dev
  assets/scss/app.scss
  templates/admin/answer/edit.html.twig
  templates/admin/answer/new.html.twig
  templates/admin/question/edit.html.twig
  templates/admin/question/index.html.twig
  templates/admin/question/show.html.twig
  templates/admin/training/edit.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/new.html.twig
  templates/admin/training/show.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_employee/show.html.twig
  templates/admin_news/edit.html.twig
  templates/admin_news/index.html.twig
  templates/admin_news/new.html.twig
  templates/admin_standard/edit.html.twig
  templates/admin_standard/index.html.twig
  templates/admin_standard/show.html.twig
  templates/advice/index.html.twig
  templates/audit/index.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/employee/index.html.twig
  templates/formations/_trainingDetails.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
  templates/home/index.html.twig
  templates/news/index.html.twig
  templates/questions/questions.html.twig
  templates/security/login.html.twig
  templates/security/resetPassword.html.twig
  templates/standards/index.html.twig
  templates/watch/index.html.twig
Labels: Reviewed by PO
