Repository WildCodeSchool/orleans-0219-php-oryalis, pull requests merged in 2019-06, with the labels that each got.

#3 Navbar crée
  assets/images/LogoTransparent.png
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/routes.yaml
  package.json
  phpstan.neon
  src/Controller/HomeController.php
  symfony.lock
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/home.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#15 Sprint01_US_03_Footer
  assets/images/logo.png
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.lock
  src/Controller/HomeController.php
  templates/_Footer.html.twig
  templates/base.html.twig
  yarn.lock
Labels: Reviewed by PO

#17 homepage section presentation
  assets/images/quality.jpg
  assets/scss/_vars.scss
  assets/scss/app.scss
  package-lock.json
  package.json
  templates/home.html.twig
  yarn.lock
Labels: Reviewed by PO

#20 Sprint1 us02 banniere
  assets/images/BannerHome.jpg
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  package.json
  phpstan.neon
  src/Controller/HomeController.php
  templates/_banner.html.twig
  templates/home.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: Reviewed by PO

#21 US_07_page_accueil_prestations
  assets/images/audit.png
  assets/images/conseil.png
  assets/images/formation.png
  assets/images/veille.png
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/home.html.twig
Labels: Reviewed by PO

#22 Dev to master
  assets/images/BannerHome.jpg
  assets/images/LogoTransparent.png
  assets/images/audit.png
  assets/images/conseil.png
  assets/images/formation.png
  assets/images/logo.png
  assets/images/quality.jpg
  assets/images/veille.png
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/routes.yaml
  package-lock.json
  package.json
  phpstan.neon
  src/Controller/HomeController.php
  symfony.lock
  templates/_Footer.html.twig
  templates/_banner.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/home.html.twig
  templates/home/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#28 FIX Navbar fixed top + responsive amélioré
  assets/scss/app.scss
  templates/_navbar.html.twig
Labels: Reviewed by PO

#29 Fix bannière
  assets/scss/app.scss
Labels: Reviewed by PO

#41 Arborescence création AdminController, appAdmin.scss, modif index de …
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/layoutVistitor.html.twig
Labels: Reviewed by PO

#44 Sprint02 us34 admin formation
  assets/images/delete-filled.png
  assets/images/edit-filled.png
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/AdminController.php
  src/DataFixtures/TrainingFixtures.php
  src/Entity/Training.php
  src/Repository/TrainingRepository.php
  symfony.lock
  templates/admin/training.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed by PO

#49 Dev
  assets/images/delete-filled.png
  assets/images/edit-filled.png
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/AdminController.php
  src/Controller/HomeController.php
  src/DataFixtures/TrainingFixtures.php
  src/Entity/Training.php
  src/Repository/TrainingRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/admin/training.html.twig
  templates/base.html.twig
  templates/home.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
  templates/layoutVistitor.html.twig
  webpack.config.js
Labels: Reviewed by PO

#52 Sprint2 us30 lister membres
  assets/images/placeholder150.png
  assets/scss/appAdmin.scss
  composer.lock
  phpstan.neon
  src/Controller/AdminEmployeeController.php
  src/DataFixtures/EmployeeFixtures.php
  src/Entity/Employee.php
  src/Form/EmployeeType.php
  src/Repository/EmployeeRepository.php
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_employee/show.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed by PO

#59 Vue utilisateur Formations
  assets/images/training.jpg
  assets/scss/app.scss
  src/Controller/TrainingController.php
  src/DataFixtures/TrainingFixtures.php
  templates/_navbar.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
Labels: Reviewed by PO

#58 Sprint02 us07 accueil/news
  assets/images/new.jpg
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/packages/twig_extensions.yaml
  phpstan.neon
  src/Controller/HomeController.php
  symfony.lock
  templates/home/index.html.twig
Labels: Corrections Done

#60 Sprint2 us33 supprimer membre
  assets/scss/appAdmin.scss
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/index.html.twig
Labels: Reviewed by PO

#62 ADD formation
  src/Controller/AdminTrainingController.php
  src/Entity/Training.php
  src/Form/TrainingType.php
  templates/admin/training/_delete_form.html.twig
  templates/admin/training/_form.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/new.html.twig
Labels: Reviewed by PO

#54 EDIT formation
  assets/scss/appAdmin.scss
  composer.lock
  src/Controller/AdminController.php
  src/Controller/TrainingController.php
  src/DataFixtures/TrainingFixtures.php
  src/Entity/Training.php
  src/Form/TrainingType.php
  templates/admin/training/edit.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/show.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed by PO

#67 Sprint3 us10 page equipe
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Controller/EmployeeController.php
  templates/_navbar.html.twig
  templates/employee/index.html.twig
Labels: Reviewed by PO

#69 Dev
  assets/images/new.jpg
  assets/images/placeholder150.png
  assets/images/training.jpg
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/packages/twig_extensions.yaml
  phpstan.neon
  src/Controller/AdminController.php
  src/Controller/AdminEmployeeController.php
  src/Controller/AdminTrainingController.php
  src/Controller/EmployeeController.php
  src/Controller/HomeController.php
  src/Controller/TrainingController.php
  src/DataFixtures/EmployeeFixtures.php
  src/DataFixtures/TrainingFixtures.php
  src/Entity/Employee.php
  src/Entity/Training.php
  src/Form/EmployeeType.php
  src/Form/TrainingType.php
  src/Repository/EmployeeRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/admin/training/_delete_form.html.twig
  templates/admin/training/_form.html.twig
  templates/admin/training/edit.html.twig
  templates/admin/training/index.html.twig
  templates/admin/training/new.html.twig
  templates/admin/training/show.html.twig
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/_form.html.twig
  templates/admin_employee/edit.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
  templates/admin_employee/show.html.twig
  templates/employee/index.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed by PO

#70 fix bracket scss
  assets/scss/app.scss
Labels: Reviewed by PO

#71 Dev
  assets/scss/app.scss
Labels: Reviewed by PO

#72 Modif condition picture -> tel
  templates/employee/index.html.twig
Labels: Corrections Done, Reviewed by PO

#74 Sprint2 us42 navbar admin
  assets/images/LogoAdmin.png
  assets/scss/_vars.scss
  assets/scss/appAdmin.scss
  templates/_navbarAdmin.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed by PO

#82 Modif des boutons et suppression du pointer sur les cards admin
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/index.html.twig
Labels: Reviewed by PO

#68 Admin Lister les News
  assets/scss/appAdmin.scss
  src/Controller/NewsController.php
  src/DataFixtures/NewsFixture.php
  src/Entity/News.php
  src/Form/NewsType.php
  src/Repository/NewsRepository.php
  templates/admin_news/_delete_form.html.twig
  templates/admin_news/_form.html.twig
  templates/admin_news/edit.html.twig
  templates/admin_news/index.html.twig
  templates/admin_news/new.html.twig
  templates/admin_news/show.html.twig
Labels: Reviewed by PO

#84 Fix Formations CSS et Bannière
  assets/scss/app.scss
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
Labels: Reviewed by PO

#85 Changement du nom de la route pour trainings_index (français)
  src/Controller/TrainingController.php
Labels: Reviewed by PO

#90 Sprint4 us15 page audit statique
  assets/images/audit.jpeg
  assets/images/audit_1.jpeg
  assets/images/audit_2.jpeg
  assets/images/audit_3.jpeg
  assets/scss/app.scss
  src/Controller/AuditController.php
  templates/_navbar.html.twig
  templates/audit/index.html.twig
Labels: Reviewed by PO

#88 Fix us10 style lien images
  assets/images/equipe_jumb.jpeg
  assets/scss/app.scss
  templates/employee/index.html.twig
Labels: Reviewed by PO

#91 Fix02 css homepage header
  assets/images/banner2.jpg
  assets/images/oryalis.jpg
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/_banner.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Reviewed by PO

#92 Dev
  assets/images/LogoAdmin.png
  assets/images/audit.jpeg
  assets/images/audit_1.jpeg
  assets/images/audit_2.jpeg
  assets/images/audit_3.jpeg
  assets/images/banner2.jpg
  assets/images/equipe_jumb.jpeg
  assets/images/oryalis.jpg
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/appAdmin.scss
  src/Controller/AuditController.php
  src/Controller/NewsController.php
  src/Controller/TrainingController.php
  src/DataFixtures/NewsFixture.php
  src/Entity/News.php
  src/Form/NewsType.php
  src/Repository/NewsRepository.php
  templates/_banner.html.twig
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/admin_employee/_delete_form.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_news/_delete_form.html.twig
  templates/admin_news/_form.html.twig
  templates/admin_news/edit.html.twig
  templates/admin_news/index.html.twig
  templates/admin_news/new.html.twig
  templates/admin_news/show.html.twig
  templates/audit/index.html.twig
  templates/base.html.twig
  templates/employee/index.html.twig
  templates/formations/show.html.twig
  templates/formations/trainingList.html.twig
  templates/home/index.html.twig
  templates/layoutAdmin.html.twig
Labels: Reviewed by PO

#87 Sprint2 us31 ajouter membre
  .gitignore
  assets/images/nicolas_champagne.jpg
  assets/scss/_vars.scss
  assets/scss/appAdmin.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Entity/Employee.php
  src/Form/EmployeeType.php
  symfony.lock
  templates/admin_employee/_form.html.twig
  templates/admin_employee/index.html.twig
  templates/admin_employee/new.html.twig
Labels: Reviewed by PO
